channels:
  - conda-forge
  - defaults
dependencies:
  - altair=4.1.0
  - geopandas=0.9.0
  - matplotlib=3.4.2
  - numpy=1.20.3
  - openpyxl=3.0.7
  - pandas=1.3.2
  - pip=21.0.1
  - pygeos=0.10.2
  - python=3.8.11
  - seaborn=0.11.2
  - plotly=5.4.0
  - pip:
    - pytopojson==1.1.1
    - streamlit==0.88.0
