name: streamlit_env
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas=0.9.0
  - geopandas-base=0.9.0
  - matplotlib-base=3.4.3
  - rtree=0.9.3
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - pip:
    - altair==4.1.0
    - numpy==1.20.1
    - pandas==1.2.3
    - streamlit==0.88.0
