# To create a conda environment from this file, run the following command in Anaconda Prompt. Replace ENV_NAME with the desired name for the new environment, and FILE_NAME with the name of this file.
# conda env create --name ENV_NAME --file FILE_NAME.yml
# 
channels:
  - conda-forge
  - defaults
dependencies:
  # python version
  - python=3.8
  # main data science packages.
  - pandas=1.5 # conda
  - numpy=1.20 # conda
  - matplotlib=3.4 # conda
  - seaborn=0.11 # conda
  - scipy=1.10 # conda
  - altair=4.1 # conda
  - geopandas=0.10 # conda
  - plotly=5.4 # conda
  - sqlite=3.41 # conda
  # other necessary packages
  - chardet=4.0 # conda. for recognizing the encoding of a text file.
  - openpyxl=3.0 # conda. for handling xlsx files.
  - python-levenshtein=0.12 # conda. for string similarity metrics
  - pygeos=0.10 # conda. for geospatial data
  - fiona=1.8 # conda. for inspecting layers of gpkg files
  - ipython-sql=0.3 # conda. provides %%sql magic for IPython
  - lxml=4.6 # conda. needed for pd.read_html().
  - xlrd=2.0 # conda. needed for pd.read_excel()
  - bcrypt=3.2 # conda. for password purposes.
  - google-auth=2.3 # conda. for accessing a private GSheets file in a Streamlit web app.
  - findspark=2.0 # conda. for finding a Spark installation. DIFFERENT from 2.0.0
  - psycopg2=2.9 # conda. for PostgreSQL.
  - pip=21.2 # conda. needed to install packages that only work when pip-installed.
  - streamlit=1.22.0 # conda. important package for simple web apps.
  - ipykernel=6.4 # conda. for using the environment as a jupyter kernel.
  - pillow=9.2 # conda. needed for altair version 4 to work properly.
  - protobuf=3.19 # conda. some versions of streamlit need this package to be version 3.20.x or lower.
  - click # conda. this package had to be installed before to avoid an error occuring in protobuf.
  - statsmodels # conda.
  - scikit-learn # conda.
  - gsheetsdb # conda. for querying data from a gsheets file.